name: ui_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  flutter_screenutil: ^5.9.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
